# coding:utf-8
# Author:hxj

IMAGE_CODE_EXPIRED_TIME = 180
SMS_CODE_EXPIRED_TIME = 300
# 短信发送间隔
SEND_SMS_CODE_EXPIRED_TIME = 60

# 登录错误尝试次数
ACCESS_NUM = 3

# redis错误尝试记录有效期
ERR_ACCESS_EXPIRE_TIME = 600